### ISSUE TITLE
通过 Fragment 跳转页面的架构不适用页面间埋点参数传递

### ISSUE THREAD

**Issue by ZDZN** [DylanCaiCoding/Tracker#1]
按照该库或者说西瓜的文章的逻辑，目前页面间埋点参数的传递是通过 intent 承载的，但如果单 Activity 多 Fragment 一类通过 Fragment 去进行页面间跳转的架构，应该暂时是无法处理页面间埋点参数的传递吧？

Fragment 的参数跳转我考虑是可以通过 arguments 承载，但还没想清楚有没有其他坑

**Comment by DylanCaiCoding** [comment]
是用 Navigation 吗？我可以考虑支持一下。可以用 arguments 传递，应该是没有问题，各个 Fragment 的 View 是平级的关系，所以 Fragment 的埋点信息都是独立的。只要把埋点参数传递到下个 Fragment 的根视图中，责任链还是完整的

**Comment by ZDZN** [comment]
感谢大佬的库，补充了西瓜文章中很多代码片段连贯上的思路
